### PR TITLE
Python3 fixes

### PR DESCRIPTION
**Pull request by apodemus**
Hi!

Thanks for maintaining an awesome library!
I've added a few small bugfixes for python3 as well as pep8 reformatting (mostly tabs -> spaces).

Cheers!

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Hi @apodemus,

What python3 issue are you trying to resolve? Please provide the smallest diff possible, and make a separate pull request for each distinct problem.
PEP8 is for the Python project, and is not required for projects written in python, nor for Python3 compatibility. Please do not change the codestyle of this project.

Cheers, 
             Johannes

**Comment by apodemus** [comment]
Hi @JohannesBuchner 

Some of your code had inconsistent use of tabs and spaces which raises a TabError in python3 - so I just reindented all your files to fix that (not really style changes in my opinion, but perhaps misleading to call it pep8, soz).  Additionally there was an AttributeError in run.py which occurs during the handling of the OSError since its 'message' attribute has been removed.  I'll make seperate (smaller) PRs if that's what you prefer...

**Comment by apodemus** [comment]
OK, trimmed down the PR to just address a single issue. :)

**Comment by JohannesBuchner** [comment]
Great, thanks. Did you test this in python2 as well?
Ultimately I would like to have automatic testing for pymultinest for such bugs (similar to imagehash https://github.com/JohannesBuchner/imagehash/blob/master/.travis.yml), but unfortunately I never have time. Even better would be some unit testing, but not sure if travis will easily allow a multinest install.

**Comment by apodemus** [comment]
Yes, its working in python 2 as well AFAICT.  Unit tests are definitely a good idea!

**Comment by vlas-sokolov** [comment]
My bad, did not see that there was already a PR on the error handling issue so I opened (and promptly closed) another one.

@apodemus there seems to be a slight advantage in using `str(e)` over `e.args[0]`, as indicated in this [SO question]( http://stackoverflow.com/a/30881390/4118756).

**Comment by apodemus** [comment]
Thanks for the tip!  Updated the PR :+1:

**Comment by JohannesBuchner** [comment]
Hi @apodemus and @vlas-sokolov,
I merged the code and released version 2.2, could you please test it (in Python2 and 3).
Thank you!

**Comment by vlas-sokolov** [comment]
@JohannesBuchner the error message is being displayed correctly for python 2.7.6 and 3.4.3.

**Pull request merged**
