### PR TITLE
Added option for multiple non-parallelised multinest runs within mpi environment

### PR DESCRIPTION
**Pull request by ACCarnall**
This is a fixed version of #125 that allows multiple non-parallelised multinest runs within an MPI environment by setting the mpi_off keyword argument in run. I'd like to include this option in an update to my public code, so if it would be possible to add this change to PyPI that would be much appreciated!

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Wouldn't it be wiser to add a environment variable for such a use case?
For example, MULTINEST_LIBNAME could have the values 'auto' (default, runs the existing library finding code), 'libmultinest_mpi.so' or 'libmultinest.so' (to force the MPI/non-MPI case, respectively).

**Comment by ACCarnall** [comment]
For me it would be useful to be able to specify which library is used when the call to pymultinest.run is made, rather than at import. Is your concern the possible unnecessary re-loading of the library within the function? The reason for this is to get around the error which was encountered with #125 . The issue is that having "lib=" within the function causes the code to treat lib as a local variable in all cases, so it won't access the global variable even in cases where lib hasn't been set within the function.

**Comment by JohannesBuchner** [comment]
Hi @ACCarnall, sorry for being inactive here. Could you describe your use case a bit more? Are you running something across many cores, and each core runs its pymultinest inference?

Is this for distributing the analysis of many independent data sets? If so, why not give each program a data set and run them independently?

**Comment by ACCarnall** [comment]
Yeah I think you understand what I'm trying to do. I have a large number of independent datasets, I want to fit all of them separately using the same model, one per core, and merge the results into a catalogue. I used to do this by invoking large numbers of separate processes that each fitted a different dataset, but I found this approach to be pretty unstable, particularly when running across multiple nodes on a cluster. The way I do this now is much neater and more user friendly, as it breaks far less often.

There isn't really a problem with bagpipes users downloading pymultinest from my forked repository, it's been working fine for the past year, but I don't really understand the issue with making these extremely minor changes? There's no change to the default behaviour of the code, it's just an extra configuration option for those who want it, and it seems like I'm not the first person who does (#125).

**Comment by JohannesBuchner** [comment]
Before the proposed change, if the import succeeds, .run will succeed.

After the proposed change, the import may succeed, but .run will fail, because the library is switched.

I think this is not so good for the user experience.

Therefore, we would have to load both libraries on import (mpi only if mpi4py import succeeds), and pick at runtime the one to use.

Regarding the code, I would like to avoid code duplication, so perhaps a function would be useful. A minor issue is mpi_off=False is a double negative, so use_MPI=True or use_MPI='auto' would be easier.

**Comment by JohannesBuchner** [comment]
@ACCarnall , could you please have a look at #173. Would it also address the problem? I have not tested the code yet.

**Comment by ACCarnall** [comment]
Hi Johannes,

I just downloaded #173 and tested it out with bagpipes, it seems to work fine with my code, thanks for sorting this out!

Cheers,
Adam

**Pull request closed without merging**
