### PR TITLE
Update library load times

### PR DESCRIPTION
**Pull request by t0rrant**
numpy by itself takes a lot of time to load. Importing it this way seems to lower load times by half, in my case.

And by the way, on  [pymultinest/analyse.py#L30](https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest/analyse.py#L30) we are importing `re` but it does not seem to be used, am I missing something?

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Hmm, interesting. I expected most applications to use and load numpy anyways.

Are the changes to shutil and tempfile necessary? They should be python-builtin modules.

**Comment by JohannesBuchner** [comment]
The re-import seems to be a leftover that can be removed.

**Comment by t0rrant** [comment]
If the re import can be removed I expect it to improve loading times even further.

Regarding using and loading numpy by most of other applications, it loads numpy multiple times from what I can tell, however I did not do exhaustive testing.

The changes to shutil and tempfile come from the rational of importing only what you need, you don't really need it but every bit counts.

**Comment by JohannesBuchner** [comment]
Could it be that you are masquerading another issue -- why do you need startup to be fast? If you have many short runs, maybe you should do a python loop over multiple pymultinest runs.

**Pull request closed without merging**
