### PR TITLE
Removed old pypolychord

### PR DESCRIPTION
**Pull request by williamjameshandley**
Could we please remove the prototype pypolychord from pymultinest. [PolyChord](https://github.com/PolyChord/PolyChordLite) now natively comes with its own up-to-date python wrapper, which has an import conflict with pymultinest's pypolychord implementation.

### CODE REVIEW

**Comment by williamjameshandley** [comment]
Also merged in a small bug-fix to the dumper function

**Comment by JohannesBuchner** [comment]
Could you please add a test for the dumper function (see tests/pymultinest_test_minimal.py)?

**Comment by JohannesBuchner** [comment]
As you can see [in the travis log](https://travis-ci.org/JohannesBuchner/PyMultiNest/builds/455517208), there are some issues with this PR: 

Python 2.7 complains that shape is not defined:
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/travis/build/JohannesBuchner/PyMultiNest/pymultinest/run.py", line 227, in dumper
    maxLogLike,logZ,logZerr, 0)
  File "/home/travis/build/JohannesBuchner/PyMultiNest/tests/pymultinest_minimal_test.py", line 33, in mydumper
    print("calling dumper", shape(physLive))
NameError: global name 'shape' is not defined
```

Python 3 complains about inconsistent use of tabs and spaces (this project uses tabs throughout).

**Comment by williamjameshandley** [comment]
@JohannesBuchner : Is there anything else that needs to be done?

**Comment by JohannesBuchner** [comment]
I made a new release, 2.7. Please check that it works for you.

**Comment by williamjameshandley** [comment]
That's working great. Thank you very much @JohannesBuchner

**Pull request merged**
