### PR TITLE
Fixes gfortran issue on MacOS

### PR DESCRIPTION
**Pull request by sahiljhawar**
please squash and merge, thank you!

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Can we make this future-proof somehow?

**Comment by JohannesBuchner** [comment]
is `which gfortran` not enough?

**Comment by sahiljhawar** [comment]
No, there are multiple versions of Fortran ie 12, 13, 14. Can definitely do some regex trickery and always get the fortran without worrying about the version.

**Comment by JohannesBuchner** [comment]
Merging this for now, thank you

**Pull request merged**
